apiVersion: v1
kind: Pod
metadata:
  name: limit-app
spec:
  containers:
  - name: python-eater
    image: python:alpine
    # สั่งให้จอง Memory 100MB แล้วหลับยาว (ไม่กิน CPU)
    command: ["python", "-c", "import time; a = 'x' * 100 * 1024 * 1024; print('Yummy!'); time.sleep(3600)"]
    resources:
      limits:
        memory: "550Mi" # เพดาน 550MB (เหลือเฟือสำหรับ 100MB)