apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-army
spec:
  # จุดสำคัญ 1: เริ่มต้นขอทหาร 2 นาย
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine