apiVersion: v1
kind: Pod
metadata:
  name: zombie-app
spec:
  containers:
  - name: zombie
    image: busybox
    # คำสั่งจำลองชีวิต:
    # 1. สร้างไฟล์หัวใจ (/tmp/healthy)
    # 2. รอ 30 วินาที (ช่วงนี้ยังแข็งแรง)
    # 3. ลบไฟล์ทิ้ง (ตาย!)
    # 4. หลับยาว (ช่วงนี้คือเป็นซอมบี้ ถ้าไม่มีใครมาจัดการ)
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
    
    # หมอตรวจชีพจร 🩺
    readinessProbe:
      exec: # ใช้วิธีรันคำสั่งเช็ค
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5 # ให้เวลาเริ่มระบบ 5 วิ
      periodSeconds: 5       # ตรวจทุกๆ 5 วิ