apiVersion: v1
kind: Pod
metadata:
  name: authorized-app
spec:
  containers:
  - name: nginx
    image: nginx:alpine
  # --- ส่วนบัตรผ่านพิเศษ ---
  tolerations:
  - key: "security"
    operator: "Equal"
    value: "high"
    effect: "NoSchedule"