apiVersion: v1
kind: Pod
metadata:
  name: gpu-app
spec:
  containers:
  - name: nginx
    image: nginx:alpine
  # --- เติมส่วนนี้ครับ ---
  # เราต้องบอกว่า 'เลือกโหนด' (nodeSelector)
  # ที่มีป้าย 'hardware' เป็น 'gpu'
  nodeSelector:
    hardware: quantum