apiVersion: v1
kind: Pod
metadata:
  name: soft-app
spec:
  containers:
  - name: nginx
    image: nginx:alpine
  affinity:
    nodeAffinity:
      # เราจะใช้แบบ 'preferred' (ชอบนะ แต่ไม่บังคับ)
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: hardware
            operator: In
            values:
            - super-computer  # <-- ลองใส่ชื่อฮาร์ดแวร์ที่ "ไม่มีอยู่จริง" ลงไปตรงนี้ครับ